services:

  nginx:
    hostname: nginx
    platform: linux/x86_64
    build: docker/nginx
    depends_on:
      - php
    environment:
      PHP_FPM_IP: php
      PHP_FPM_PORT: 9000
    ports:
      - "${APP_PORT:-8000}:80"
    volumes:
      - .:/app

  php:
    hostname: php
    platform: linux/x86_64
    build:
      context: docker/php
      target: dev
      args:
        - PHP_VERSION=${PHP_VERSION:-8.0}
    ports:
      - "${PHP_PORT:-9000}:9000"
      - "${XDEBUG_CLIENT_PORT:-9003}:9003"
    volumes:
      - .:/app
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/php-overrides.ini:/usr/local/etc/php/conf.d/php-overrides.ini
